name: duff_talk
description: "Offline ASL letter image recognition."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.8.5
  image: ^4.2.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/sign_mnist_float32.tflite
    - assets/models/labels_map.json
